GET http://localhost:8080/pet

###
GET http://localhost:8080/pet/6

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Beagle",
    "rating": 4.5,
    "deskripsi": "Memiliki corak dengan kombinasi 3 warna. Ramah, sangat aktif, gesit, setia, dan pintar.",
    "jumlah_terjual": 10,
    "harga": "Rp800.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Cavalier King Charles Spaniel",
    "rating": 5.0,
    "deskripsi": "Memiliki corak Blenheim (merah kastanye dan putih). Periang, lembut, dan tak kenal takut.",
    "jumlah_terjual": 6,
    "harga": "Rp134.000.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Pomeranian",
    "rating": 4.5,
    "deskripsi": "Memiliki corak warna cream dan putih. Sangat lincah, cerdas, dan imut.",
    "jumlah_terjual": 15,
    "harga": "Rp900.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Poodle",
    "rating": 5.0,
    "deskripsi": "Memiliki corak warna coklat. Pandai, ceria, selalu waspada, dan memiliki insting yang tajam.",
    "jumlah_terjual": 18,
    "harga": "Rp800.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Anggora",
    "rating": 5.0,
    "deskripsi": "Suka bermain, sangat aktif, riuh, dan suka mencari perhatian pemiliknya.",
    "jumlah_terjual": 18,
    "harga": "Rp650.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Singapura",
    "rating": 4.0,
    "deskripsi": "Periang, selalu ingin tahu, senang bermain, tidak akan merusak barang di sekitarnya, dan interaktif.",
    "jumlah_terjual": 6,
    "harga": "Rp18.500.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Russian Blue",
    "rating": 4.5,
    "deskripsi": "Cerdas dan lucu, tetapi cenderung pemalu di sekitar orang asing.",
    "jumlah_terjual": 12,
    "harga": "Rp2.500.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Balinese",
    "rating": 5.0,
    "deskripsi": "Sangat aktif, menyenangkan, dan suka bermain dengan pemiliknya.",
    "jumlah_terjual": 15,
    "harga": "Rp4.000.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Nuri",
    "rating": 4.0,
    "deskripsi": "Memiliki bulu berwarna merah dan suara yang merdu, serta mampu menirukan suara manusia.",
    "jumlah_terjual": 18,
    "harga": "Rp800.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Kakatua",
    "rating": 4.5,
    "deskripsi": "Penuh kasih sayang, lucu, dan jail.",
    "jumlah_terjual": 14,
    "harga": "Rp3.800.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Burung Hantu",
    "rating": 5.0,
    "deskripsi": "Pendengar yang baik, memiliki penglihatan yang tajam, pendiam, sederhana, dan bijak.",
    "jumlah_terjual": 20,
    "harga": "Rp500.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Beo",
    "rating": 4.5,
    "deskripsi": "Ramah, lucu, suka berbicara, dan suka bernyanyi mengikuti suara yang didengar.",
    "jumlah_terjual": 16,
    "harga": "Rp1.000.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Kelinci Holland Lop",
    "rating": 5.0,
    "deskripsi": "Sangat enerjik, aktif, dan bersahabat, namun sulit digendong dan dipegang.",
    "jumlah_terjual": 20,
    "harga": "Rp300.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Landak Mini Salt and Pepper",
    "rating": 3.0,
    "deskripsi": "Jinak, pemalu, dan penakut. Durinya tidak berbahaya dan aman.",
    "jumlah_terjual": 5,
    "harga": "Rp220.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "American Guinea Pig",
    "rating": 4.5,
    "deskripsi": "Ramah dan senang bermain dengan anak-anak.",
    "jumlah_terjual": 17,
    "harga": "Rp330.000,00"
}

###
POST http://localhost:8080/pet
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Tupai Merah",
    "rating": 4.0,
    "deskripsi": "Berani, agresif, suka beraktifitas, dan pandai.",
    "jumlah_terjual": 12,
    "harga": "Rp175.000,00"
}

###
GET http://localhost:8080/product

###
GET http://localhost:8080/product/6

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "A-Frame Rumah Anjing",
    "rating": 4.5,
    "deskripsi": "Rumah anjing sederhana untuk hewan peliharaan anda dengan berbahan dasar kayu.",
    "jumlah_terjual": 12,
    "harga": "Rp543.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Pedigree",
    "rating": 5.0,
    "deskripsi": "Mengandung nutrisi yang baik untuk membangun sistem kekebalan tubuh.",
    "jumlah_terjual": 24,
    "harga": "Rp43.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Good Dog",
    "rating": 4.5,
    "deskripsi": "Makanan anjing super premium yang mengandung asam amino lemak, vitamin, dan mineral.",
    "jumlah_terjual": 17,
    "harga": "Rp67.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Anjing",
    "nama": "Happy Dog",
    "rating": 5.0,
    "deskripsi": "Makanan kering dengan daging domba bergizi, nasi yang mudah dicerna, dan lemak yang rendah.",
    "jumlah_terjual": 20,
    "harga": "Rp70.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Kandang Kucing Mini Portabel",
    "rating": 5.0,
    "deskripsi": "Kandang kucing mini portabel yang praktis dibawa ke mana saja yang terbuat dari plastik.",
    "jumlah_terjual": 21,
    "harga": "Rp85.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Whiskas Adult Cat Food Tuna",
    "rating": 5.0,
    "deskripsi": "Mengandung serat untuk pencernaan, kalsium, omega 6, vitamin, taurine, dan antioksida.",
    "jumlah_terjual": 25,
    "harga": "Rp70.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Friskies Adult Seafood Sensations",
    "rating": 4.5,
    "deskripsi": "Makanan kucing berkualitas yang mengandung nutrisi lengkap dan seimbang dari Purina.",
    "jumlah_terjual": 18,
    "harga": "Rp56.500,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Kucing",
    "nama": "Happy Cat Minkas Perfect Mix",
    "rating": 5.0,
    "deskripsi": "Mengandung protein unggas, daging domba, dan ikan, yang kaya akan omega 3 dan omega 6.",
    "jumlah_terjual": 15,
    "harga": "Rp110.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Sangkar Burung Putih",
    "rating": 5.0,
    "deskripsi": "Sangkar burung elegan berwarna putih. Berbahan besi dengan diameter 22 cm dan tinggi 25 cm.",
    "jumlah_terjual": 12,
    "harga": "Rp125.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Vitakraft",
    "rating": 5.0,
    "deskripsi": "Dapat mencegah gejala kekurangan gizi dan membantu mengoptimalkan perawatan.",
    "jumlah_terjual": 22,
    "harga": "Rp80.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Pakan Pleci Nutri Booster",
    "rating": 4.0,
    "deskripsi": "Mengandung vitamin yang tinggi, nutrisi, protein, dan karbohidrat.",
    "jumlah_terjual": 15,
    "harga": "Rp35.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Burung",
    "nama": "Premia Spring",
    "rating": 4.5,
    "deskripsi": "Mengandung nutrisi makro, vitamin, dan mineral yang lengkap untuk burung peliharaan anda.",
    "jumlah_terjual": 12,
    "harga": "Rp80.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Rumah Hamster Pink",
    "rating": 5.0,
    "deskripsi": "Rumah tempat bermain dan beristirahat untuk hamster kesayangan anda.",
    "jumlah_terjual": 18,
    "harga": "Rp120.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "SmartHeart Rabbit Food",
    "rating": 5.0,
    "deskripsi": "Makanan lengkap untuk kelinci yang diperkaya dengan sayuran dan sereal.",
    "jumlah_terjual": 20,
    "harga": "Rp40.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Hedgehog Food",
    "rating": 4.5,
    "deskripsi": "Makanan landak yang mengandung omega 3, 6, 9, protein, vitamin, dan kalium.",
    "jumlah_terjual": 12,
    "harga": "Rp27.000,00"
}

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "kategori": "Hewan Mungil",
    "nama": "Vitakraft Guinea Pig",
    "rating": 4.5,
    "deskripsi": "Mengandung vitamin yang diperkaya oleh extra dosis vitamin C yang penting untuk kesehatan.",
    "jumlah_terjual": 15,
    "harga": "Rp40.000,00"
}